In [2]:
TODAY="2021-11-13"
TASK = "phylogenetic-determination"
DIR = "$(homedir())/$(TODAY)-$(TASK)"
if !isdir(DIR)
    mkdir(DIR)
end
cd(DIR)

In [3]:
import Pkg

pkgs = [
"JSON",
"HTTP",
"Dates",
"uCSV",
"DelimitedFiles",
"DataFrames",
"ProgressMeter",
"BioSequences",
"FASTX",
"Distances",
"Plots",
"StatsPlots",
"StatsBase",
"Statistics",
"Mmap",
"MultivariateStats",
"PyCall",
"Random",
"Primes",
"Revise",
"SparseArrays",
"SHA",
"Mycelia",
"GenomicAnnotations",
"BioFetch",
"Combinatorics",
"StaticArrays",
"BioSymbols",
"RollingFunctions",
"OrderedCollections"
]

for pkg in pkgs
    try
        eval(Meta.parse("import $pkg"))
    catch
        Pkg.add(pkg)
        eval(Meta.parse("import $pkg"))
    end
end

In [27]:
function generate_all_possible_kmers(k, alphabet)
    kmer_iterator = Iterators.product([alphabet for i in 1:k]...)
    kmer_vectors = collect.(vec(collect(kmer_iterator)))
    if eltype(alphabet) == BioSymbols.AminoAcid
        kmers = BioSequences.LongAminoAcidSeq.(kmer_vectors)
    elseif eltype(alphabet) == BioSymbols.DNA
        kmers = BioSequences.LongDNASeq.(kmer_vectors)
    else
        error()
    end
    return sort!(kmers)
end

function generate_all_possible_canonical_kmers(k, alphabet)
    kmers = generate_all_possible_kmers(k, alphabet)
    if eltype(alphabet) == BioSymbols.AminoAcid
        return kmers
    elseif eltype(alphabet) == BioSymbols.DNA
        return BioSequences.DNAMer.(unique!(BioSequences.canonical.(kmers)))
    else
        error()
    end
end

generate_all_possible_canonical_kmers (generic function with 1 method)

In [35]:
function count_canonical_aamers(k, fasta_proteins)
    aamer_counts = OrderedCollections.OrderedDict{BioSequences.LongAminoAcidSeq, Int64}()
    for protein in fasta_proteins
        s = FASTX.sequence(protein)
        these_counts = sort(StatsBase.countmap([s[i:i+k-1] for i in 1:length(s)-1]))
        merge!(+, aamer_counts, these_counts)
    end
    return sort(aamer_counts)
end

count_canonical_aamers (generic function with 1 method)

In [24]:
function update_counts_matrix!(matrix, sample_index, countmap, sorted_kmers)
    for (i, kmer) in enumerate(sorted_kmers)
        matrix[i, sample_index] = get(countmap, kmer, 0)
    end
    return matrix
end

update_counts_matrix! (generic function with 1 method)

In [62]:
function accession_list_to_aamer_counts_table(accession_list, k, AA_ALPHABET)
    
    canonical_aamers = generate_all_possible_canonical_kmers(k, AA_ALPHABET)
    
    aamer_counts_matrix = zeros(length(canonical_aamers), length(accession_list))
    
    ProgressMeter.@showprogress for (entity_index, accession) in enumerate(accession_list)
        entity_genbank = BioFetch.fetchseq(accession, format = BioFetch.gb)
        fasta_proteins = Vector{FASTX.FASTA.Record}()
        for gene in GenomicAnnotations.@genes(entity_genbank, CDS)
            try
                dna_seq = GenomicAnnotations.sequence(gene)
                # if seq isn't divisible by 3, cut final bases that can't be mapped to a codon
                translateable_length = div(length(dna_seq), 3) * 3
                truncated_dna_seq = dna_seq[1:translateable_length]
                aa_seq = BioSequences.translate(truncated_dna_seq)
                id = getproperty(gene, :protein_id)
                product = getproperty(gene, :product)
                record = FASTX.FASTA.Record(id, product, aa_seq)
                push!(fasta_proteins, record)
            catch
                @error GenomicAnnotations.sequence(gene)
                error()
            end

        end
# #         fasta_proteins = 
# #             [
# #                 [FASTX.FASTA.Record(getproperty(gene, :protein_id),
# #                                     getproperty(gene, :product),
# #                                     GenomicAnnotations.sequence(gene; translate = true)
# #                                 )
# #                     for gene in GenomicAnnotations.@genes(chromosome, CDS)
# #                 ]
# #                         for chromosome in entity_genbank
# #             ]
#         fasta_proteins =
#                 [
#                                     ,
                                    
#                                 )
#                     for gene in 
#                 ]
#         @show fasta_proteins
        entity_aamer_counts = count_canonical_aamers(aa_k, fasta_proteins)
        update_counts_matrix!(aamer_counts_matrix, entity_index, entity_aamer_counts, canonical_aamers)
    end
    return aamer_counts_matrix
end

accession_list_to_aamer_counts_table (generic function with 2 methods)

In [65]:
function accession_list_to_dnamer_counts_table(accession_list, k)
    canonical_dnamers = generate_all_possible_canonical_kmers(k, DNA_ALPHABET)
    dnamer_counts_matrix = zeros(length(canonical_dnamers), length(accession_list))

    ProgressMeter.@showprogress for (entity_index, accession) in enumerate(accession_list)
        entity_genbank = BioFetch.fetchseq(accession, format = BioFetch.gb)
        fasta_dna_sequences = [
            FASTX.FASTA.Record(chromosome.name, chromosome.sequence) 
                for chromosome in entity_genbank
                              ]
        entity_dnamer_counts = Mycelia.count_canonical_kmers(BioSequences.DNAMer{dna_k}, fasta_dna_sequences)
        update_counts_matrix!(dnamer_counts_matrix, entity_index, entity_dnamer_counts, canonical_dnamers)
    end
    return dnamer_counts_matrix    
end

accession_list_to_dnamer_counts_table (generic function with 2 methods)

In [89]:
function normalize_distance_matrix(distance_matrix)
    return distance_matrix ./ maximum(distance_matrix)
end

normalize_distance_matrix (generic function with 1 method)

In [74]:
function counts_matrix_to_euclidean_distance_matrix(counts_matrix)
    n_samples = size(counts_matrix, 2)
    distance_matrix = zeros(n_samples, n_samples)
    for x1 in 1:n_samples
        x1_values = counts_matrix[:, x1]
        for x2 in 2:n_samples
            x2_values = counts_matrix[:, x2]
            d = Distances.euclidean(x1_values, x2_values)
            distance_matrix[x1, x2] = distance_matrix[x2, x1] = d
        end
    end
    return distance_matrix
end

counts_matrix_to_euclidean_distance_matrix (generic function with 1 method)

In [75]:
function counts_matrix_to_js_divergence_matrix(counts_matrix)
    n_samples = size(counts_matrix, 2)
    distance_matrix = zeros(n_samples, n_samples)
    for x1 in 1:n_samples
        x1_values = counts_matrix[:, x1] ./ sum(counts_matrix[:, x1])
        for x2 in 2:n_samples
            x2_values = counts_matrix[:, x2] ./ sum(counts_matrix[:, x2])
            d = Distances.js_divergence(x1_values, x2_values)
            distance_matrix[x1, x2] = distance_matrix[x2, x1] = d
        end
    end
    return distance_matrix
end

counts_matrix_to_js_divergence_matrix (generic function with 1 method)

In [77]:
function counts_matrix_to_jaccard_distance_matrix(counts_matrix)
    n_samples = size(counts_matrix, 2)
    distance_matrix = zeros(n_samples, n_samples)
    for x1 in 1:n_samples
        x1_values = counts_matrix[:, x1] .> 0
        for x2 in 2:n_samples
            x2_values = counts_matrix[:, x2] .> 0
            d = Distances.jaccard(x1_values, x2_values)
            distance_matrix[x1, x2] = distance_matrix[x2, x1] = d
        end
    end
    return distance_matrix
end

counts_matrix_to_jaccard_distance_matrix (generic function with 1 method)

In [6]:
# MYCELIA_METADATA = joinpath(Pkg.dir("Mycelia"), "metadata")
MYCELIA_METADATA = joinpath(dirname(dirname(pathof(Mycelia))),  "metadata")

"/home/jupyter-cjprybol/.julia/dev/Mycelia/metadata"

In [7]:
# https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/virus?SeqType_s=Nucleotide&VirusLineage_ss=Bacteriophage,%20all%20taxids&Completeness_s=complete
entity_metadata = DataFrames.DataFrame(uCSV.read("$(MYCELIA_METADATA)/2021-11-13-ncbi-complete-bacteriophage.csv", header=1, quotes='"')...)
entity_metadata = entity_metadata[entity_metadata[!, "Nuc_Completeness"] .== "complete", :]
entity_metadata = entity_metadata[entity_metadata[!, "Sequence_Type"] .== "RefSeq", :]
sort!(entity_metadata, "Accession")

4569×23 DataFrame
  Row │ Accession    SRA_Accession  Submitters                         Release ⋯
      │ String       String         String                             String  ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │ NC_000866.4                 Miller,E.S., Kutter,E., Mosig,G.…  1999-07 ⋯
    2 │ NC_000867.1                 Kivela,H.M., Mannisto,R.H., Kalk…  1999-07
    3 │ NC_000871.1                 Desiere,F., Lucchini,S., Brussow…  1999-07
    4 │ NC_000872.1                 Desiere,F., Lucchini,S., Brussow…  1999-07
    5 │ NC_000896.1                 Altermann,E., Klein,J.R., Henric…  1999-08 ⋯
    6 │ NC_000902.1                 Miyamoto,H., Nakai,W., Yajima,N.…  1999-09
    7 │ NC_000924.1                 Plunkett,G. III, Rose,D.J., Durf…  1999-04
    8 │ NC_000929.1                 Morgan,G.J., Hatfull,G.F., Casje…  1999-10
    9 │ NC_000935.1                 van der Wilk,F., Dullemans,A.M.,…  1999-10 ⋯
   10 │ NC_001271.1                 Pajunen,M.I., Kiljunen,S.J., Sod…  1999-12
   11 │ NC_001317.1                 Portelli,R., Dodd,I.B., Xue,Q., …  1995-09
  ⋮   │      ⋮             ⋮                        ⋮                          ⋱
 4560 │ NC_055914.1                 Ismail,A., Veeramachaneni,S., Fr…  2021-06
 4561 │ NC_055915.1                 Hoetzinger,M., Nilsson,E., Holmf…  2021-06 ⋯
 4562 │ NC_055916.1                 Liu,A.A., Ma,F.F.                  2021-06
 4563 │ NC_055917.1                 Brown,N.J., Benedetto,N.J., Temp…  2021-06
 4564 │ NC_055918.1                 Adkins,J.M., Alame,N.W., Araujo,…  2021-06
 4565 │ NC_055919.1                 Li,S., Lin,Y.                      2021-06 ⋯
 4566 │ NC_055920.1                 Dennis,E.A., Alston,T.C., Buckle…  2021-06
 4567 │ NC_055921.1                 Shang,Y.                           2021-06
 4568 │ NC_055956.1                 Dunstan,R.A., Pickard,D., Lithgo…  2021-10
 4569 │ NC_056724.1                 Mahanivong,C., Boyce,J.D., David…  2021-08 ⋯
                                                20 columns and 4548 rows omitted

In [8]:
Random.seed!(0)
n_samples = 10
subset_indices = StatsBase.sample(1:size(entity_metadata, 1), n_samples, ordered=true, replace=false)
entity_metadata = entity_metadata[subset_indices, :]
# n_samples = size(entity_metadata, 1)

10×23 DataFrame
 Row │ Accession    SRA_Accession  Submitters                         Release_ ⋯
     │ String       String         String                             String   ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ NC_005355.1                 Ventura,M., Canchaya,C., Pridmor…  2004-01- ⋯
   2 │ NC_020844.1                 Henn,M.R., Dillon,J., Levin,J., …  2013-03-
   3 │ NC_022057.1                 Farina,J., Richards,K., Hiller,J…  2013-08-
   4 │ NC_027365.1                 Hatfull,G.F., Jamborcic,A., Chen…  2015-06-
   5 │ NC_028667.1                 Pourcel,C., Midoux,C., Bourkalts…  2015-12- ⋯
   6 │ NC_028974.1                 Djamen,P.Y., Nguyen,L., Gibbs,Z.…  2016-01-
   7 │ NC_031230.1                 Bandyopadhyay,A., Carlton,M.L., …  2016-09-
   8 │ NC_047712.1                 Gregory,A.C., LaButti,K., Copela…  2020-05-
   9 │ NC_051670.1                 Alvarez,R.V., Connors,B., Jenkin…  2020-11- ⋯
  10 │ NC_054986.1                 Pujato,S.A., Guglielmotti,D.M., …  2021-05-
                                                              20 columns omitted

In [9]:
# download genomic fasta files
show(entity_metadata, allcols=true)

10×23 DataFrame
 Row │ Accession    SRA_Accession  Submitters                         Release_Date          Isolate    Species                            Genus           Family        Molecule_type  Length  Sequence_Type  Nuc_Completeness  Genotype  Segment  Publications  Geo_Location                      Country  USA     Host                               Isolation_Source  Collection_Date  BioSample  GenBank_Title                     
     │ String       String         String                             String                String     String                             String          String        String         Int64   String         String            String    String   String        String                            String   String  String                             String            String           String     String                            
─────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

In [ ]:
dna_k = 5
aa_k = 2

AA_ALPHABET = collect(filter(x -> x != BioSequences.AA_Term, Mycelia.AA_ALPHABET))
DNA_ALPHABET = Mycelia.DNA_ALPHABET

In [64]:
accession_list = entity_metadata[!, "Accession"]
aa_k = 2
AA_ALPHABET
aamer_counts_matrix = accession_list_to_aamer_counts_table(accession_list, aa_k, AA_ALPHABET)

Progress: 100%|█████████████████████████████████████████| Time: 0:00:08


484×10 Matrix{Float64}:
  48.0  119.0  329.0  374.0  223.0  385.0  270.0  289.0  260.0   6.0
  27.0   79.0  166.0  175.0  102.0  152.0  191.0  172.0  133.0  13.0
  56.0   48.0   57.0   62.0   42.0   55.0   82.0  220.0   50.0  42.0
  38.0   88.0  128.0  147.0  100.0  136.0  180.0  218.0  124.0  36.0
   3.0   11.0   36.0   20.0   13.0   19.0   28.0   34.0   24.0   0.0
  44.0   55.0   79.0   99.0   77.0   87.0  103.0  151.0   66.0  26.0
  61.0  108.0  192.0  208.0  125.0  174.0  194.0  246.0  136.0  16.0
  52.0  104.0  193.0  196.0  125.0  202.0  197.0  318.0  177.0  44.0
   8.0   17.0   43.0   43.0   27.0   43.0   62.0   62.0   46.0   2.0
  68.0   50.0  118.0   98.0   80.0   62.0  143.0  246.0   77.0  50.0
  72.0  108.0  201.0  189.0  135.0  163.0  238.0  313.0  149.0  40.0
 103.0   51.0   91.0   68.0   51.0   64.0  120.0  256.0   76.0  28.0
  17.0   26.0   50.0   40.0   39.0   44.0   52.0   88.0   28.0  11.0
   ⋮                                  ⋮                         
   0.0    0.0 

In [67]:
dna_k = 5
dnamer_counts_matrix = accession_list_to_dnamer_counts_table(accession_list, dna_k)

Progress: 100%|█████████████████████████████████████████| Time: 0:00:08


512×10 Matrix{Float64}:
 395.0  102.0   27.0   15.0   14.0    3.0   17.0  304.0   42.0  213.0
 182.0   92.0   30.0   25.0   29.0   12.0   42.0  461.0   68.0  130.0
 270.0  108.0   19.0   16.0   22.0    7.0   35.0  370.0   28.0  135.0
 315.0   57.0   24.0    8.0    6.0    5.0   17.0  305.0   23.0  174.0
 173.0   76.0   25.0   18.0   29.0    6.0   61.0  683.0   76.0  108.0
  74.0   86.0   84.0   59.0   54.0   24.0  110.0  683.0  148.0   79.0
  68.0   95.0   66.0   43.0   46.0   33.0   77.0  237.0   79.0   78.0
 166.0   67.0   18.0   12.0   25.0    8.0   45.0  847.0   50.0   93.0
 267.0   91.0   33.0   18.0   33.0   16.0   51.0  776.0   36.0   78.0
 184.0  123.0   52.0   42.0   47.0    6.0   51.0  236.0   66.0   84.0
 121.0   73.0   24.0   19.0   33.0   19.0   61.0  531.0   51.0   66.0
 178.0   62.0   16.0   16.0   14.0   11.0   40.0  545.0   36.0   93.0
 252.0   33.0    7.0    6.0    7.0    1.0   17.0  497.0   12.0  189.0
   ⋮                                  ⋮                         
 

In [87]:
euclidean_distance_matrix = counts_matrix_to_euclidean_distance_matrix(aamer_counts_matrix)

10×10 Matrix{Float64}:
    0.0     363.395   930.143   828.972  …  3426.15   676.033   292.828
  363.395     0.0     740.48    616.57      3407.29   462.511   431.268
  930.143   740.48      0.0     365.032     2883.35   401.759  1084.02
  828.972   616.57    365.032     0.0       3126.63   323.5     946.88
  481.347   291.405   681.845   508.162     3417.06   423.458   542.825
  799.046   585.655   435.738   284.974  …  3184.68   324.302   897.018
 1249.0    1114.11    547.489   790.581     2478.87   818.754  1436.61
 3426.15   3407.29   2883.35   3126.63         0.0   3131.89   3626.07
  676.033   462.511   401.759   323.5       3131.89     0.0     785.882
  292.828   431.268  1084.02    946.88      3626.07   785.882     0.0

10×10 Matrix{Float64}:
 0.0        0.100217   0.256515  0.228614   …  0.944867  0.186437   0.0807562
 0.100217   0.0        0.20421   0.170038      0.939666  0.127551   0.118935
 0.256515   0.20421    0.0       0.100669      0.795172  0.110797   0.298952
 0.228614   0.170038   0.100669  0.0           0.862263  0.0892149  0.261131
 0.132746   0.0803639  0.18804   0.140141      0.942359  0.116782   0.149701
 0.220361   0.161512   0.120168  0.0785902  …  0.878272  0.0894363  0.24738
 0.34445    0.30725    0.150987  0.218027      0.683623  0.225796   0.39619
 0.944867   0.939666   0.795172  0.862263      0.0       0.863715   1.0
 0.186437   0.127551   0.110797  0.0892149     0.863715  0.0        0.216731
 0.0807562  0.118935   0.298952  0.261131      1.0       0.216731   0.0

In [86]:
jaccard_distance_matrix = counts_matrix_to_jaccard_distance_matrix(aamer_counts_matrix)

10×10 Matrix{Float64}:
 0.0        0.0075  0.0075  0.01       …  0.0075  0.0075  0.0075  0.0678392
 0.0075     0.0     0.0     0.0025        0.0     0.0     0.0     0.07
 0.0075     0.0     0.0     0.0025        0.0     0.0     0.0     0.07
 0.01       0.0025  0.0025  0.0           0.0025  0.0025  0.0025  0.0676692
 0.0125313  0.01    0.01    0.0125        0.01    0.01    0.01    0.0703518
 0.0075     0.0     0.0     0.0025     …  0.0     0.0     0.0     0.07
 0.0075     0.0     0.0     0.0025        0.0     0.0     0.0     0.07
 0.0075     0.0     0.0     0.0025        0.0     0.0     0.0     0.07
 0.0075     0.0     0.0     0.0025        0.0     0.0     0.0     0.07
 0.0678392  0.07    0.07    0.0676692     0.07    0.07    0.07    0.0

In [90]:
normalized_jaccard_distance_matrix = normalize_distance_matrix(jaccard_distance_matrix)

10×10 Matrix{Float64}:
 0.0       0.106607   0.106607   0.142143   …  0.106607   0.106607   0.964286
 0.106607  0.0        0.0        0.0355357     0.0        0.0        0.995
 0.106607  0.0        0.0        0.0355357     0.0        0.0        0.995
 0.142143  0.0355357  0.0355357  0.0           0.0355357  0.0355357  0.961869
 0.178124  0.142143   0.142143   0.177679      0.142143   0.142143   1.0
 0.106607  0.0        0.0        0.0355357  …  0.0        0.0        0.995
 0.106607  0.0        0.0        0.0355357     0.0        0.0        0.995
 0.106607  0.0        0.0        0.0355357     0.0        0.0        0.995
 0.106607  0.0        0.0        0.0355357     0.0        0.0        0.995
 0.964286  0.995      0.995      0.961869      0.995      0.995      0.0

In [91]:
js_divergence_matrix = counts_matrix_to_js_divergence_matrix(aamer_counts_matrix)
normalized_js_divergence_matrix = normalize_distance_matrix(js_divergence_matrix)

10×10 Matrix{Float64}:
 0.0       0.392346  0.577981   0.733273  …  0.198749  0.600575   0.20184
 0.392346  0.0       0.150022   0.244279     0.279905  0.170571   0.570267
 0.577981  0.150022  0.0        0.112222     0.373758  0.0740063  0.763536
 0.733273  0.244279  0.112222   0.0          0.544724  0.113679   0.903351
 0.59137   0.209471  0.170857   0.172598     0.504903  0.186445   0.752823
 0.827008  0.302399  0.15205    0.128813  …  0.597838  0.151395   1.0
 0.420278  0.11946   0.100075   0.2094       0.256556  0.121783   0.592963
 0.198749  0.279905  0.373758   0.544724     0.0       0.378828   0.244621
 0.600575  0.170571  0.0740063  0.113679     0.378828  0.0        0.757206
 0.20184   0.570267  0.763536   0.903351     0.244621  0.757206   0.0

In [ ]:
unique_species = filter(!isempty, sort(unique(reference_phage_metadata[!, "Species"])))
unique_genera = filter(!isempty, sort(unique(reference_phage_metadata[!, "Genus"])))
unique_families = filter(!isempty, sort(unique(reference_phage_metadata[!, "Family"])))

Euclidean seems better than cosine distance
Is jensen shannon divergence better than euclidean
mash with k=13 and s=1_000 was not good
try smaller 9
try larger s

In [ ]:
# distance_matrix = distance_matrix_raw_kmer_counts_euclidean
# distance_metric = "euclidean"

# distance_matrix = distance_matrix_raw_kmer_counts_cosine
# distance_metric = "cosine"

# distance_matrix = distance_matrix_raw_kmer_probability_js_divergence
# distance_metric = "js_divergence"

# distance_matrix = mash_distance_matrix
# distance_metric = "mash"

distance_matrix = ani_distance_matrix
distance_metric = "ani"

In [ ]:
intra_species_distances = Float64[]
inter_species_distances = Float64[]
ProgressMeter.@showprogress for species in unique_species
    species_indices = findall(reference_phage_metadata[!, "Species"] .== species)
    other_species_indices = setdiff(1:size(distance_matrix, 1), species_indices)
    for index in species_indices
        other_indices = filter(i -> i != index, species_indices)
        append!(intra_species_distances, vec(distance_matrix[index, other_indices]))
        append!(inter_species_distances, vec(distance_matrix[index, other_species_indices]))
    end
end

In [ ]:
StatsBase.describe(StatsBase.sample(inter_species_distances, 10_000))

In [ ]:
StatsBase.describe(StatsBase.sample(intra_species_distances, 10_000))

In [ ]:
n_points = 1_000
p = StatsPlots.scatter(
    [
        [rand(Bool) ? 1 + rand()/3 : 1 - rand()/3 for i in 1:n_points],
        [rand(Bool) ? 2 + rand()/3 : 2 - rand()/3 for i in 1:n_points]
    ],
    [
        StatsBase.sample(intra_species_distances, n_points),
        StatsBase.sample(inter_species_distances, n_points)
    ],
    label = ["within species" "between species"],
    legend = :outertopright,
    alpha = 0.5,
    title = "$(distance_metric) distance @ k=$k"
)
p = StatsPlots.hline(p,
    [Statistics.mean(intra_species_distances) + 3*Statistics.std(intra_species_distances)],
    label="mean + 3σ"
)
StatsPlots.savefig(p, "$DIR/$(distance_metric)-distance-species-k$k.png")
StatsPlots.savefig(p, "$DIR/$(distance_metric)-distance-species-k$k.svg")
p

In [ ]:
intra_genera_distances = Float64[]
inter_genera_distances = Float64[]
ProgressMeter.@showprogress for genus in unique_genera
    genus_indices = findall(reference_phage_metadata[!, "Genus"] .== genus)
    other_genera_indices = setdiff(1:1:size(distance_matrix, 1), genus_indices)
    for index in genus_indices
        other_indices = filter(i -> i != index, genus_indices)
        append!(intra_genera_distances, vec(distance_matrix[index, other_indices]))
        append!(inter_genera_distances, vec(distance_matrix[index, other_genera_indices]))
    end
end

In [ ]:
StatsBase.describe(StatsBase.sample(inter_genera_distances, 10_000))

In [ ]:
StatsBase.describe(StatsBase.sample(intra_genera_distances, 10_000))

In [ ]:
n_points = 1_000
p = StatsPlots.scatter(
    [
        [rand(Bool) ? 1 + rand()/3 : 1 - rand()/3 for i in 1:n_points],
        [rand(Bool) ? 2 + rand()/3 : 2 - rand()/3 for i in 1:n_points]
    ],
    [
        StatsBase.sample(intra_genera_distances, n_points),
        StatsBase.sample(inter_genera_distances, n_points)
    ],
    label = ["within genera" "between genera"],
    legend = :outertopright,
    alpha = 0.5,
    title = "$(distance_metric) distance @ k=$k"
)
p = StatsPlots.hline(p,
    [Statistics.mean(intra_genera_distances) + 3*Statistics.std(intra_genera_distances)],
    label="mean + 3σ"
)
StatsPlots.savefig(p, "$DIR/$(distance_metric)-distance-genus-k$k.png")
StatsPlots.savefig(p, "$DIR/$(distance_metric)-distance-genus-k$k.svg")
p

In [ ]:
intra_family_distances = Float64[]
inter_family_distances = Float64[]
ProgressMeter.@showprogress for family in unique_families
    family_indices = findall(reference_phage_metadata[!, "Family"] .== family)
    other_family_indices = setdiff(1:1:size(distance_matrix, 1), family_indices)
    for index in family_indices
        other_indices = filter(i -> i != index, family_indices)
        append!(intra_family_distances, vec(distance_matrix[index, other_indices]))
        append!(inter_family_distances, vec(distance_matrix[index, other_family_indices]))
    end
end

In [ ]:
StatsBase.describe(StatsBase.sample(inter_family_distances, 10_000))

In [ ]:
StatsBase.describe(StatsBase.sample(intra_family_distances, 10_000))

In [ ]:
n_points = 1_000
p = StatsPlots.scatter(
    [
        [rand(Bool) ? 1 + rand()/3 : 1 - rand()/3 for i in 1:n_points],
        [rand(Bool) ? 2 + rand()/3 : 2 - rand()/3 for i in 1:n_points]
    ],
    [
        StatsBase.sample(intra_family_distances, n_points),
        StatsBase.sample(inter_family_distances, n_points)
    ],
    label = ["within families" "between families"],
    legend = :outertopright,
    alpha = 0.5,
    title = "$(distance_metric) distance @ k=$k"
)
p = StatsPlots.hline(p,
    [Statistics.mean(intra_family_distances) + 3*Statistics.std(intra_family_distances)],
    label="mean + 3σ"
)
StatsPlots.savefig(p, "$DIR/$(distance_metric)-distance-family-k$k.png")
StatsPlots.savefig(p, "$DIR/$(distance_metric)-distance-family-k$k.svg")
p

In [ ]:
# kmer_counts_matrix = nothing
# distance_matrix_raw_kmer_counts_cosine = nothing
# distance_matrix_raw_kmer_counts_euclidean = nothing
# GC.gc()