In [1]:
# if hit plotting library issues, try resetting LD path for julia
# can set in ~/.local/share/jupyter/kernels/
haskey(ENV, "LD_LIBRARY_PATH") && @assert ENV["LD_LIBRARY_PATH"] == ""
import Pkg
pkgs = [
    "Revise",
    "FASTX",
    "BioSequences",
    "Kmers",
    "Graphs",
    "MetaGraphs",
    "SparseArrays",
    "ProgressMeter",
    "Distributions",
    "HiddenMarkovModels",
    "BioAlignments",
    "StatsBase",
    "Random",
    "StatsPlots",
    "Statistics",
    "IterTools",
    "Primes",
    "OnlineStats",
    "IteratorSampling",
    "HypothesisTests",
    "Clustering",
    "Distances",
    "BioAlignments",
    "Statistics",
    "Primes",
    "DataFrames",
    "BioSymbols",
    "LinearAlgebra"
]
# Pkg.add(pkgs)
for pkg in pkgs
    eval(Meta.parse("import $pkg"))
end
# Pkg.develop(path="/global/cfs/projectdirs/m4269/cjprybol/Mycelia")
# Pkg.develop(path="../../..")
import Mycelia

┌ Warning: The active manifest file is an older format with no julia version entry. Dependencies may have been resolved with a different julia version.
└ @ /global/cfs/cdirs/m4269/cjprybol/Mycelia/Manifest.toml:0
[ Info: Precompiling Mycelia [453d265d-8292-4a7b-a57c-dce3f9ae6acd]
[ Info: Skipping precompilation since __precompile__(false). Importing Mycelia [453d265d-8292-4a7b-a57c-dce3f9ae6acd].


In [2]:
PROJECT_BASEDIR = dirname(pwd())
data_dir = joinpath(PROJECT_BASEDIR, "data")
genome_dir = mkpath(joinpath(data_dir, "genomes"))

"/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/genomes"

In [3]:
working_dir = joinpath(data_dir, "test")
mkpath(working_dir)

"/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/test"

In [4]:
short_read_sets = unique(map(x -> match(r"^(.+\.\d+x)\.", x).captures[1], filter(x -> occursin(r"\.fna\.art", x) && occursin(r"\.fq\.gz", x) && !occursin("trimming_report", x) && !occursin("_val_", x), sort(readdir(genome_dir, join=true), by=x->filesize(x)))))


18-element Vector{SubString{String}}:
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 68 bytes ⋯ ".fna.normalized.vcf.fna.art.10x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 69 bytes ⋯ "fna.normalized.vcf.fna.art.100x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 71 bytes ⋯ ".fna.normalized.vcf.fna.art.10x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 76 bytes ⋯ ".fna.normalized.vcf.fna.art.10x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 70 bytes ⋯ "na.normalized.vcf.fna.art.1000x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 77 bytes ⋯ "fna.normalized.vcf.fna.art.100x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 72 bytes ⋯ "fna.normalized.vcf.fna.art.100x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 73 bytes ⋯ ".fna.normalized.vcf.fna.art.10x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 76 bytes ⋯ ".fna.normalized.vcf.fna.art.10x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 76 bytes ⋯ ".fna.normalized.vcf.fna.art.10x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 78 bytes ⋯ "na.normalized.vcf.fna.art.1000x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 73 bytes ⋯ "na.normaliz

In [5]:
# short_read_set = short_read_sets[1]
# short_read_set = short_read_sets[2]
# short_read_set = short_read_sets[3]
# short_read_set = short_read_sets[4]
# short_read_set = short_read_sets[5]
# short_read_set = short_read_sets[6]
# 2 hours
short_read_set = short_read_sets[7]

"/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/genomes/3NEzu1DmBy.fna.normalized.vcf.fna.art.100x"

In [6]:
forward = short_read_set * ".1_val_1.fq.gz"
reverse = short_read_set * ".2_val_2.fq.gz"

"/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/genomes/3NEzu1DmBy.fna.normalized.vcf.fna.art.100x.2_val_2.fq.gz"

In [7]:
short_read_set_joint_fastq = short_read_set * ".joint.fq.gz"
if !isfile(short_read_set_joint_fastq)
    run(pipeline(`cat $(forward) $(reverse)`, short_read_set_joint_fastq))
end
short_read_set_joint_fastq
original_fastq = short_read_set_joint_fastq

"/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/genomes/3NEzu1DmBy.fna.normalized.vcf.fna.art.100x.joint.fq.gz"

In [8]:
# almost no time at all for short reads
# polishing_results = Mycelia.iterative_polishing(original_fastq)

In [10]:
# assembly_fastq = last(polishing_results).fastq
assembly_fastq = "/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/genomes/3NEzu1DmBy.fna.normalized.vcf.fna.art.100x.joint.k11.k13.k17.k19.k23.k31.k53.k89.fq.gz"

"/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/genomes/3NEzu1DmBy.fna.normalized.vcf.fna.art.100x.joint.k11.k13.k17.k19.k23.k31.k53.k89.fq.gz"

In [11]:
# assembly_k = last(polishing_results).k
assembly_k = 89

89

In [12]:
mean_read_length = Statistics.mean([length(FASTX.sequence(record)) for record in Mycelia.open_fastx(assembly_fastq)])

147.80863636363637

In [13]:
kmer_graph = Mycelia.build_directed_kmer_graph(fastq=assembly_fastq, k=assembly_k)

{21503, 21478} directed Int64 metagraph with Float64 weights defined by :weight (default weight 1.0)

In [14]:
# heuristic - should be based on something better or removed altogether
max_filter = 5

initial_connected_components = length(Graphs.connected_components(kmer_graph))
coverage_threshold = 1
tresholded_vertices = [i for (i, (kmer, count)) in enumerate(MetaGraphs.get_prop(kmer_graph, :kmer_counts)) if count > coverage_threshold]
candidate_subgraph, vertex_map = Graphs.induced_subgraph(kmer_graph, tresholded_vertices)
while (length(Graphs.connected_components(candidate_subgraph)) == initial_connected_components) && (coverage_threshold < max_filter)
    coverage_threshold += 1
    tresholded_vertices = [i for (i, (kmer, count)) in enumerate(MetaGraphs.get_prop(kmer_graph, :kmer_counts)) if count > coverage_threshold]
    candidate_subgraph, vertex_map = Graphs.induced_subgraph(kmer_graph, tresholded_vertices)
end
coverage_threshold -= 1
@show coverage_threshold

tresholded_vertices = [i for (i, (kmer, count)) in enumerate(MetaGraphs.get_prop(kmer_graph, :kmer_counts)) if count > coverage_threshold]
filtered_graph, filtered_graph_vertex_map = Graphs.induced_subgraph(kmer_graph, tresholded_vertices)
# candidate_subgraph, vertex_map = Graphs.induced_subgraph(kmer_graph, [v for v in Graphs.vertices(kmer_graph) if kmer_graph.vprops[v][:count] >= coverage_threshold])

coverage_threshold = 0


({21503, 21478} directed Int64 metagraph with Float64 weights defined by :weight (default weight 1.0), [1, 2, 3, 4, 5, 6, 7, 8, 9, 10  …  21494, 21495, 21496, 21497, 21498, 21499, 21500, 21501, 21502, 21503])

In [15]:
connected_components = sort(Graphs.connected_components(filtered_graph), by=x->length(x), rev=true)

25-element Vector{Vector{Int64}}:
 [4, 5, 8, 12, 13, 14, 17, 18, 20, 21  …  21485, 21486, 21492, 21493, 21496, 21497, 21498, 21501, 21502, 21503]
 [1, 3, 6, 9, 10, 15, 16, 19, 22, 24  …  21484, 21487, 21488, 21489, 21490, 21491, 21494, 21495, 21499, 21500]
 [7, 126, 131, 134, 139, 140, 147, 150, 151, 155  …  21220, 21253, 21254, 21277, 21304, 21339, 21340, 21408, 21410, 21412]
 [200, 234, 236, 237, 457, 458, 474, 718, 762, 763  …  21145, 21146, 21176, 21275, 21276, 21296, 21299, 21330, 21375, 21376]
 [2, 11, 67, 68, 322, 323, 936, 937, 1308, 1309  …  19401, 19402, 19669, 19670, 20002, 20003, 20144, 20145, 20917, 20918]
 [128, 136, 545, 559, 1158, 1810, 2246, 2300, 2484, 3532  …  17755, 18137, 18404, 18429, 18444, 18455, 18479, 19264, 20764, 21336]
 [129, 137, 546, 560, 1159, 1695, 1811, 2247, 2301, 2485  …  17756, 18138, 18405, 18430, 18445, 18456, 18480, 19265, 20765, 21337]
 [130, 138, 547, 561, 1160, 1812, 2248, 2302, 2486, 3849  …  18139, 18406, 18431, 18446, 18457, 18485, 18530, 1

In [18]:
connected_components = filter(cc -> length(cc) > 1, connected_components)

24-element Vector{Vector{Int64}}:
 [4, 5, 8, 12, 13, 14, 17, 18, 20, 21  …  21485, 21486, 21492, 21493, 21496, 21497, 21498, 21501, 21502, 21503]
 [1, 3, 6, 9, 10, 15, 16, 19, 22, 24  …  21484, 21487, 21488, 21489, 21490, 21491, 21494, 21495, 21499, 21500]
 [7, 126, 131, 134, 139, 140, 147, 150, 151, 155  …  21220, 21253, 21254, 21277, 21304, 21339, 21340, 21408, 21410, 21412]
 [200, 234, 236, 237, 457, 458, 474, 718, 762, 763  …  21145, 21146, 21176, 21275, 21276, 21296, 21299, 21330, 21375, 21376]
 [2, 11, 67, 68, 322, 323, 936, 937, 1308, 1309  …  19401, 19402, 19669, 19670, 20002, 20003, 20144, 20145, 20917, 20918]
 [128, 136, 545, 559, 1158, 1810, 2246, 2300, 2484, 3532  …  17755, 18137, 18404, 18429, 18444, 18455, 18479, 19264, 20764, 21336]
 [129, 137, 546, 560, 1159, 1695, 1811, 2247, 2301, 2485  …  17756, 18138, 18405, 18430, 18445, 18456, 18480, 19265, 20765, 21337]
 [130, 138, 547, 561, 1160, 1812, 2248, 2302, 2486, 3849  …  18139, 18406, 18431, 18446, 18457, 18485, 18530, 1

In [19]:
length.(connected_components)

24-element Vector{Int64}:
 9632
 9497
  589
  521
  111
   62
   62
   62
   62
   62
   62
   62
   62
   62
   62
   61
   61
   61
   60
   60
   59
   59
   59
   52

In [21]:
connected_component_sequences = BioSequences.LongDNA{2}[]
for connected_component in connected_components
    connected_component_subgraph, connected_component_subgraph_vertex_map = Graphs.induced_subgraph(filtered_graph, connected_component)
    sorted_connected_component_subgraph = Graphs.topological_sort_by_dfs(connected_component_subgraph)
    dsp_result = Graphs.dijkstra_shortest_paths(connected_component_subgraph, first(sorted_connected_component_subgraph))
    maxdist, maxdist_index = findmax(map(d -> d == Inf ? zero(d) : d, dsp_result.dists))
    connected_component_subgraph_longest_path = Graphs.enumerate_paths(dsp_result, maxdist_index)
    # @show connected_component_subgraph_longest_path
    original_graph_kmer_indices = filtered_graph_vertex_map[connected_component_subgraph_vertex_map[connected_component_subgraph_longest_path]]
    connected_component_subgraph_longest_path_reconstructed_sequence = Mycelia.kmer_path_to_sequence(kmer_graph.gprops[:ordered_kmers][original_graph_kmer_indices])
    push!(connected_component_sequences, connected_component_subgraph_longest_path_reconstructed_sequence)
end
connected_component_sequences
length.(connected_component_sequences)

24-element Vector{Int64}:
 1403
 1739
  267
  359
  150
  150
  150
  150
  150
  150
  150
  150
  150
  150
  150
  149
  149
  149
  148
  148
  147
  147
  147
  140

In [22]:
# first_sequence_canonical_kmers = unique(last.(collect(Kmers.EveryCanonicalKmer{Kmers.DNAKmer{assembly_k}}(connected_component_sequences[1]))))
# second_sequence_canonical_kmers = unique(last.(collect(Kmers.EveryCanonicalKmer{Kmers.DNAKmer{assembly_k}}(connected_component_sequences[2]))))
# intersect(first_sequence_canonical_kmers, second_sequence_canonical_kmers)

In [23]:
assembled_contig_quality_table = DataFrames.DataFrame()
for (i, connected_component_sequence) in enumerate(connected_component_sequences)
    this_table = Mycelia.assess_assembly_quality(assembled_sequence=connected_component_sequence, fastq=original_fastq)
    this_table[!, "contig"] .= "$(i)"
    this_table[!, "contig_length"] .= length(connected_component_sequence)
    append!(assembled_contig_quality_table, this_table)
end
assembled_contig_quality_table

Progress: 100%|█████████████████████████████████████████| Time: 0:00:11
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 

168×6 DataFrame
 Row │ k      cosine_distance  js_divergence  qv        contig  contig_length 
     │ Int64  Float64          Float64        Float64   String  Int64         
─────┼────────────────────────────────────────────────────────────────────────
   1 │    11      0.0                    0.0  Inf       1                1403
   2 │    13      0.0                    0.0  Inf       1                1403
   3 │    17      2.22045e-16            0.0  Inf       1                1403
   4 │    19      2.22045e-16            0.0  Inf       1                1403
   5 │    23      0.0                    0.0  Inf       1                1403
   6 │    31      0.0                    0.0  Inf       1                1403
   7 │    53      0.0                    0.0  Inf       1                1403
   8 │    11      0.0                    0.0  Inf       2                1739
   9 │    13      0.0                    0.0  Inf       2                1739
  10 │    17      2.22045e-16            0.0  Inf       2                1739
  11 │    19      2.22045e-16            0.0  Inf       2                1739
  ⋮  │   ⋮           ⋮               ⋮           ⋮        ⋮           ⋮
 159 │    23      0.0                    0.0   28.4984  23                147
 160 │    31      0.0                    0.0   24.9758  23                147
 161 │    53      0.0                    0.0   20.9586  23                147
 162 │    11      0.0                    0.0  Inf       24                140
 163 │    13      0.0                    0.0  Inf       24                140
 164 │    17      2.22045e-16            0.0  Inf       24                140
 165 │    19      2.22045e-16            0.0  Inf       24                140
 166 │    23      0.0                    0.0  Inf       24                140
 167 │    31      0.0                    0.0  Inf       24                140
 168 │    53      0.0                    0.0  Inf       24                140
                                                              147 rows omitted

In [24]:
function find_canonical_kmer_overlaps(sequences, k)
    sequence_canonical_kmers = keys.(Mycelia.count_canonical_kmers.(Kmers.DNAKmer{k}, sequences))
    canonical_kmer_intersect_sizes = zeros(length(sequence_canonical_kmers), length(sequence_canonical_kmers))
    for (a, aset) in enumerate(sequence_canonical_kmers)
        for (b, bset) in enumerate(sequence_canonical_kmers)
            canonical_kmer_intersect_sizes[a, b] = length(intersect(aset, bset))
        end
    end
    canonical_kmer_intersect_sizes
end

function find_best_kmer_intersect(canonical_kmer_intersect_sizes)
    off_diagonal_mask = .!Matrix(LinearAlgebra.I, size(canonical_kmer_intersect_sizes))
    max_off_diagonal_score = maximum(canonical_kmer_intersect_sizes[off_diagonal_mask])
    @assert max_off_diagonal_score > 0
    return findfirst(canonical_kmer_intersect_sizes .== max_off_diagonal_score)
end

function dna_pair_align(seq1, seq2, scoremodel = BioAlignments.AffineGapScoreModel(BioAlignments.EDNAFULL, gap_open=-5, gap_extend=-1))
    BioAlignments.pairalign(BioAlignments.OverlapAlignment(), seq1, seq2, scoremodel)
end

function find_best_alignment(seq1, seq2, scoremodel = BioAlignments.AffineGapScoreModel(BioAlignments.EDNAFULL, gap_open=-5, gap_extend=-1))
    forward_alignment = dna_pair_align(seq1, seq2, scoremodel)
    reverse_complement_alignment = dna_pair_align(seq1, BioSequences.reverse_complement(seq2), scoremodel)
    if BioAlignments.score(forward_alignment) > BioAlignments.score(reverse_complement_alignment)
        best_alignment = forward_alignment
    else
        best_alignment = reverse_complement_alignment
    end
    return best_alignment
end

function pairwise_align_sequences(sequences)
    best_pairwise_alignments = Array{Any}(undef, length(sequences), length(sequences))
    ProgressMeter.@showprogress for (a, a_seq) in enumerate(sequences)
        for (b, b_seq) in enumerate(sequences)
            best_pairwise_alignments[a, b] = find_best_alignment(a_seq, b_seq)
        end
    end
    best_pairwise_alignments
end

function find_best_alignment(best_pairwise_alignments)
    alignment_scores = BioAlignments.score.(best_pairwise_alignments)
    off_diagonal_mask = .!Matrix(LinearAlgebra.I, size(best_pairwise_alignments))
    max_off_diagonal_score = maximum(alignment_scores[off_diagonal_mask])
    return findfirst(alignment_scores .== max_off_diagonal_score)
end

"""
pass in alignment_result.aln or BioAlignments.alignment(alignment_result)
"""
function consensus_sequence(alignment)
    consensus_symbols = BioSymbols.DNA[]
    for alignment_tuple in collect(alignment)
        push!(consensus_symbols, rand(filter(x -> x != BioSymbols.DNA_Gap, alignment_tuple)))
    end
    consensus_seq = BioSequences.LongDNA{2}(consensus_symbols)
    return consensus_seq
end

consensus_sequence

In [25]:
assembly_sequences = deepcopy(connected_component_sequences)

24-element Vector{BioSequences.LongSequence{BioSequences.DNAAlphabet{2}}}:
 TTATTAGCCACGAGCCCTTTTAGAAATTCATTTTAGTTC…AACCCGAGTACTAGGTCATAAGGGAAGTATCAAGGCTGC
 TTAGTCCTGAGTGCACTAAATAATTAACAGCTTCCTTTG…GGTGGCTGGCGGCGTTGTCTTTAAAAACACTGCACTGCT
 TCACCGCGTTAGTCGCCTTTGGGAGCTATCCGAGTGCTT…GGGGTAAAGCAGTGCAGTGTTTTTAAAGACAACGCCGCC
 TTACTTTCGTTCCTTCAAGCATAGGAGTCACGTTTCCAG…AAACGGCGCGGGAGCTCTTAGCGGAAATCGTTATTACGC
 GACAGCTCTCTGGGGATGAGCGCAGTGTGCTCTATAAGT…ACTTCCCTTATGACCTAGTACTCGGGTTTCTTAAATATT
 CGCTGCCGTCTAGGCTCCAAACGTCATCTACCCATAAAC…CGAAGGTCCTGAGATAGCTCTCACGAATCCTCTAGAGTG
 GCTGCCGTCTAGGCTCCAAACGTCATCTACCCATAAACG…GAAGGTCCTGAGATAGCTCTCACGAATCCTCTAGAGTGG
 CGCTGCCGTCTAGTCTCCAAACGTCATCTACCCATAAAC…CGAAGGTCCTGAGATAGCTCTCACGAATCCTCTAGAGTG
 TCTGCCGTTCGGCCCTAGGTTTCCTCCAACCGCTGCCGT…GCAGTACGCCCTCGAGCCAAAAACACCACTCGAAGGTCC
 CTCTCCCAGTTGTGGTGTTTACGGTCAGTAGACAACTCG…TAGGCGCCTTTGGGAGCTATCCGAGTGCTTGCAAGGCCG
 GTCAGTAGACAACTCGGATGTCACAAACTCGCTAAATTA…AGTGCTTGCAAGGCCGTTCTGCCGTTCGGCCCTAGGTTT
 GTTGTGGTGTTTACGGTCAGTAGACAACTCGGA

KeyError: KeyError: key "usage_request" not found

In [26]:
canonical_kmer_intersect_sizes = find_canonical_kmer_overlaps(assembly_sequences, assembly_k)
max_canonical_kmer_intersect_index = find_best_kmer_intersect(canonical_kmer_intersect_sizes)
best_alignment = find_best_alignment(assembly_sequences[[Tuple(max_canonical_kmer_intersect_index)...]]..., BioAlignments.AffineGapScoreModel(BioAlignments.EDNAFULL, gap_open=-5, gap_extend=-2))

LoadError: AssertionError: max_off_diagonal_score > 0

In [27]:
# alignment_consensus = consensus_sequence(BioAlignments.alignment(best_alignment))
# assembly_sequences = [alignment_consensus, [assembly_sequence for (i, assembly_sequence) in enumerate(assembly_sequences) if !(i in Tuple(max_canonical_kmer_intersect_index))]...]
# canonical_kmer_intersect_sizes = find_canonical_kmer_overlaps(assembly_sequences, assembly_k)
# max_canonical_kmer_intersect_index = find_best_kmer_intersect(canonical_kmer_intersect_sizes)
# best_alignment = find_best_alignment(assembly_sequences[[Tuple(max_canonical_kmer_intersect_index)...]]..., BioAlignments.AffineGapScoreModel(BioAlignments.EDNAFULL, gap_open=-5, gap_extend=-2))

In [28]:
# alignment_consensus = consensus_sequence(BioAlignments.alignment(best_alignment))

In [30]:
final_assembly_sequences = assembly_sequences

24-element Vector{BioSequences.LongSequence{BioSequences.DNAAlphabet{2}}}:
 TTATTAGCCACGAGCCCTTTTAGAAATTCATTTTAGTTC…AACCCGAGTACTAGGTCATAAGGGAAGTATCAAGGCTGC
 TTAGTCCTGAGTGCACTAAATAATTAACAGCTTCCTTTG…GGTGGCTGGCGGCGTTGTCTTTAAAAACACTGCACTGCT
 TCACCGCGTTAGTCGCCTTTGGGAGCTATCCGAGTGCTT…GGGGTAAAGCAGTGCAGTGTTTTTAAAGACAACGCCGCC
 TTACTTTCGTTCCTTCAAGCATAGGAGTCACGTTTCCAG…AAACGGCGCGGGAGCTCTTAGCGGAAATCGTTATTACGC
 GACAGCTCTCTGGGGATGAGCGCAGTGTGCTCTATAAGT…ACTTCCCTTATGACCTAGTACTCGGGTTTCTTAAATATT
 CGCTGCCGTCTAGGCTCCAAACGTCATCTACCCATAAAC…CGAAGGTCCTGAGATAGCTCTCACGAATCCTCTAGAGTG
 GCTGCCGTCTAGGCTCCAAACGTCATCTACCCATAAACG…GAAGGTCCTGAGATAGCTCTCACGAATCCTCTAGAGTGG
 CGCTGCCGTCTAGTCTCCAAACGTCATCTACCCATAAAC…CGAAGGTCCTGAGATAGCTCTCACGAATCCTCTAGAGTG
 TCTGCCGTTCGGCCCTAGGTTTCCTCCAACCGCTGCCGT…GCAGTACGCCCTCGAGCCAAAAACACCACTCGAAGGTCC
 CTCTCCCAGTTGTGGTGTTTACGGTCAGTAGACAACTCG…TAGGCGCCTTTGGGAGCTATCCGAGTGCTTGCAAGGCCG
 GTCAGTAGACAACTCGGATGTCACAAACTCGCTAAATTA…AGTGCTTGCAAGGCCGTTCTGCCGTTCGGCCCTAGGTTT
 GTTGTGGTGTTTACGGTCAGTAGACAACTCGGA

In [31]:
sum(length.(final_assembly_sequences))

6742

In [32]:
assembly_fasta = replace(assembly_fastq, Mycelia.FASTQ_REGEX => ".assembly_k$(assembly_k).fna")
open(assembly_fasta, "w") do io
    fastx_io = FASTX.FASTA.Writer(io)
    for (i, sequence) in enumerate(final_assembly_sequences)
        identifier = "contig$(i)_length=$(length(sequence))"
        fasta_record = FASTX.FASTA.Record(identifier, sequence)
        write(fastx_io, fasta_record)
    end
    close(fastx_io)
end
assembly_fasta

"/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/genomes/3NEzu1DmBy.fna.normalized.vcf.fna.art.100x.joint.k11.k13.k17.k19.k23.k31.k53.k89.assembly_k89.fna"