In [1]:
# if hit plotting library issues, try resetting LD path for julia
# can set in ~/.local/share/jupyter/kernels/
haskey(ENV, "LD_LIBRARY_PATH") && @assert ENV["LD_LIBRARY_PATH"] == ""
import Pkg
pkgs = [
    "Revise",
    "FASTX",
    "BioSequences",
    "Kmers",
    "Graphs",
    "MetaGraphs",
    "SparseArrays",
    "ProgressMeter",
    "Distributions",
    "HiddenMarkovModels",
    "BioAlignments",
    "StatsBase",
    "Random",
    "StatsPlots",
    "Statistics",
    # "GraphMakie",
    "IterTools",
    "Primes",
    "OnlineStats",
    "IteratorSampling",
    "HypothesisTests",
    "Clustering",
    "Distances",
    "BioAlignments",
    "Statistics",
    "Primes",
    "DataFrames",
    "BioSymbols",
    "LinearAlgebra"
]
# Pkg.add(pkgs)
for pkg in pkgs
    eval(Meta.parse("import $pkg"))
end
# Pkg.develop(path="/global/cfs/projectdirs/m4269/cjprybol/Mycelia")
# Pkg.develop(path="../../..")
import Mycelia

┌ Warning: The active manifest file is an older format with no julia version entry. Dependencies may have been resolved with a different julia version.
└ @ /global/cfs/cdirs/m4269/cjprybol/Mycelia/Manifest.toml:0
[ Info: Precompiling Mycelia [453d265d-8292-4a7b-a57c-dce3f9ae6acd]
[ Info: Skipping precompilation since __precompile__(false). Importing Mycelia [453d265d-8292-4a7b-a57c-dce3f9ae6acd].


In [2]:
PROJECT_BASEDIR = dirname(pwd())
data_dir = joinpath(PROJECT_BASEDIR, "data")
genome_dir = mkpath(joinpath(data_dir, "genomes"))

"/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/genomes"

In [3]:
working_dir = joinpath(data_dir, "test")
mkpath(working_dir)

"/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/test"

In [4]:
short_read_sets = unique(map(x -> match(r"^(.+\.\d+x)\.", x).captures[1], filter(x -> occursin(r"\.fna\.art", x) && occursin(r"\.fq\.gz", x) && !occursin("trimming_report", x) && !occursin("_val_", x), sort(readdir(genome_dir, join=true), by=x->filesize(x)))))


18-element Vector{SubString{String}}:
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 68 bytes ⋯ ".fna.normalized.vcf.fna.art.10x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 69 bytes ⋯ "fna.normalized.vcf.fna.art.100x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 71 bytes ⋯ ".fna.normalized.vcf.fna.art.10x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 76 bytes ⋯ ".fna.normalized.vcf.fna.art.10x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 70 bytes ⋯ "na.normalized.vcf.fna.art.1000x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 77 bytes ⋯ "fna.normalized.vcf.fna.art.100x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 72 bytes ⋯ "fna.normalized.vcf.fna.art.100x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 73 bytes ⋯ ".fna.normalized.vcf.fna.art.10x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 76 bytes ⋯ ".fna.normalized.vcf.fna.art.10x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 76 bytes ⋯ ".fna.normalized.vcf.fna.art.10x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 78 bytes ⋯ "na.normalized.vcf.fna.art.1000x"
 "/global/cfs/cdirs/m4269/cjprybo" ⋯ 73 bytes ⋯ "na.normaliz

In [5]:
# short_read_set = short_read_sets[1]
# short_read_set = short_read_sets[2]
# short_read_set = short_read_sets[3]
# short_read_set = short_read_sets[4]
# short_read_set = short_read_sets[5]
short_read_set = short_read_sets[6]

"/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/genomes/GCF_001610725.1.fna.normalized.vcf.fna.art.100x"

In [6]:
forward = short_read_set * ".1_val_1.fq.gz"
reverse = short_read_set * ".2_val_2.fq.gz"

"/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/genomes/GCF_001610725.1.fna.normalized.vcf.fna.art.100x.2_val_2.fq.gz"

In [7]:
short_read_set_joint_fastq = short_read_set * ".joint.fq.gz"
if !isfile(short_read_set_joint_fastq)
    run(pipeline(`cat $(forward) $(reverse)`, short_read_set_joint_fastq))
end
short_read_set_joint_fastq
original_fastq = short_read_set_joint_fastq

"/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/genomes/GCF_001610725.1.fna.normalized.vcf.fna.art.100x.joint.fq.gz"

In [8]:
# almost no time at all for short reads
# polishing_results = Mycelia.iterative_polishing(original_fastq)

In [10]:
# assembly_fastq = last(polishing_results).fastq
assembly_fastq = "/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/genomes/GCF_001610725.1.fna.normalized.vcf.fna.art.100x.joint.k11.k13.k17.k19.k23.k31.k53.k89.fq.gz"

"/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/genomes/GCF_001610725.1.fna.normalized.vcf.fna.art.100x.joint.k11.k13.k17.k19.k23.k31.k53.k89.fq.gz"

In [11]:
# assembly_k = last(polishing_results).k
assembly_k = 89

89

In [12]:
mean_read_length = Statistics.mean([length(FASTX.sequence(record)) for record in Mycelia.open_fastx(assembly_fastq)])

146.3679411764706

In [13]:
kmer_graph = Mycelia.build_directed_kmer_graph(fastq=assembly_fastq, k=assembly_k)

{21020, 21007} directed Int64 metagraph with Float64 weights defined by :weight (default weight 1.0)

In [14]:
# heuristic - should be based on something better or removed altogether
max_filter = 5

initial_connected_components = length(Graphs.connected_components(kmer_graph))
coverage_threshold = 1
tresholded_vertices = [i for (i, (kmer, count)) in enumerate(MetaGraphs.get_prop(kmer_graph, :kmer_counts)) if count > coverage_threshold]
candidate_subgraph, vertex_map = Graphs.induced_subgraph(kmer_graph, tresholded_vertices)
while (length(Graphs.connected_components(candidate_subgraph)) == initial_connected_components) && (coverage_threshold < max_filter)
    coverage_threshold += 1
    tresholded_vertices = [i for (i, (kmer, count)) in enumerate(MetaGraphs.get_prop(kmer_graph, :kmer_counts)) if count > coverage_threshold]
    candidate_subgraph, vertex_map = Graphs.induced_subgraph(kmer_graph, tresholded_vertices)
end
coverage_threshold -= 1
@show coverage_threshold

tresholded_vertices = [i for (i, (kmer, count)) in enumerate(MetaGraphs.get_prop(kmer_graph, :kmer_counts)) if count > coverage_threshold]
filtered_graph, filtered_graph_vertex_map = Graphs.induced_subgraph(kmer_graph, tresholded_vertices)
# candidate_subgraph, vertex_map = Graphs.induced_subgraph(kmer_graph, [v for v in Graphs.vertices(kmer_graph) if kmer_graph.vprops[v][:count] >= coverage_threshold])

coverage_threshold = 0


({21020, 21007} directed Int64 metagraph with Float64 weights defined by :weight (default weight 1.0), [1, 2, 3, 4, 5, 6, 7, 8, 9, 10  …  21011, 21012, 21013, 21014, 21015, 21016, 21017, 21018, 21019, 21020])

In [15]:
connected_components = sort(Graphs.connected_components(filtered_graph), by=x->length(x), rev=true)

13-element Vector{Vector{Int64}}:
 [1, 4, 5, 15, 19, 23, 24, 25, 26, 29  …  20980, 20981, 20990, 20992, 20993, 20994, 21008, 21009, 21013, 21019]
 [3, 13, 14, 20, 21, 22, 28, 35, 39, 42  …  20989, 20998, 21000, 21003, 21005, 21007, 21011, 21015, 21016, 21020]
 [2, 6, 7, 10, 11, 12, 16, 27, 30, 31  …  20910, 20913, 20919, 20923, 20930, 20936, 20953, 20979, 20985, 20995]
 [17, 46, 89, 104, 112, 116, 132, 134, 135, 136  …  20991, 20996, 20997, 21004, 21006, 21010, 21012, 21014, 21017, 21018]
 [331, 332, 333, 334, 436, 864, 865, 866, 867, 868  …  20528, 20529, 20530, 20531, 20532, 20769, 20802, 20804, 20805, 20806]
 [18, 51, 118, 150, 317, 474, 679, 680, 681, 682  …  19513, 19780, 19781, 20482, 20483, 20484, 20554, 20615, 20616, 20617]
 [237, 238, 620, 621, 709, 752, 753, 1121, 1122, 1123  …  20808, 20809, 20894, 20911, 20944, 20958, 20959, 20999, 21001, 21002]
 [8, 32, 82, 84, 106, 113, 122, 218, 221, 280  …  17655, 18289, 18744, 18745, 18821, 18822, 19219, 19223, 19224, 19964]
 [9, 33, 8

In [16]:
length.(connected_components)

13-element Vector{Int64}:
 5070
 4836
 4724
 4686
  695
  333
  305
  136
  101
   61
   56
   12
    5

In [17]:
connected_component_sequences = BioSequences.LongDNA{2}[]
for connected_component in connected_components
    connected_component_subgraph, connected_component_subgraph_vertex_map = Graphs.induced_subgraph(filtered_graph, connected_component)
    sorted_connected_component_subgraph = Graphs.topological_sort_by_dfs(connected_component_subgraph)
    dsp_result = Graphs.dijkstra_shortest_paths(connected_component_subgraph, first(sorted_connected_component_subgraph))
    maxdist, maxdist_index = findmax(map(d -> d == Inf ? zero(d) : d, dsp_result.dists))
    connected_component_subgraph_longest_path = Graphs.enumerate_paths(dsp_result, maxdist_index)
    # @show connected_component_subgraph_longest_path
    original_graph_kmer_indices = filtered_graph_vertex_map[connected_component_subgraph_vertex_map[connected_component_subgraph_longest_path]]
    connected_component_subgraph_longest_path_reconstructed_sequence = Mycelia.kmer_path_to_sequence(kmer_graph.gprops[:ordered_kmers][original_graph_kmer_indices])
    push!(connected_component_sequences, connected_component_subgraph_longest_path_reconstructed_sequence)
end
connected_component_sequences
length.(connected_component_sequences)

13-element Vector{Int64}:
 4974
 1479
 1774
 3836
  165
  202
  171
  178
  149
  149
  144
  100
   93

In [18]:
# first_sequence_canonical_kmers = unique(last.(collect(Kmers.EveryCanonicalKmer{Kmers.DNAKmer{assembly_k}}(connected_component_sequences[1]))))
# second_sequence_canonical_kmers = unique(last.(collect(Kmers.EveryCanonicalKmer{Kmers.DNAKmer{assembly_k}}(connected_component_sequences[2]))))
# intersect(first_sequence_canonical_kmers, second_sequence_canonical_kmers)

In [19]:
assembled_contig_quality_table = DataFrames.DataFrame()
for (i, connected_component_sequence) in enumerate(connected_component_sequences)
    this_table = Mycelia.assess_assembly_quality(assembled_sequence=connected_component_sequence, fastq=original_fastq)
    this_table[!, "contig"] .= "$(i)"
    this_table[!, "contig_length"] .= length(connected_component_sequence)
    append!(assembled_contig_quality_table, this_table)
end
assembled_contig_quality_table

Progress:  86%|███████████████████████████████████▏     |  ETA: 0:00:02

KeyError: KeyError: key "usage_request" not found

Progress: 100%|█████████████████████████████████████████| Time: 0:00:12
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:01


91×6 DataFrame
 Row │ k      cosine_distance  js_divergence  qv        contig  contig_length 
     │ Int64  Float64          Float64        Float64   String  Int64         
─────┼────────────────────────────────────────────────────────────────────────
   1 │    11              0.0            0.0  Inf       1                4974
   2 │    13              0.0            0.0  Inf       1                4974
   3 │    17              0.0            0.0  Inf       1                4974
   4 │    19              0.0            0.0  Inf       1                4974
   5 │    23              0.0            0.0  Inf       1                4974
   6 │    31              0.0            0.0  Inf       1                4974
   7 │    53              0.0            0.0  Inf       1                4974
   8 │    11              0.0            0.0  Inf       2                1479
   9 │    13              0.0            0.0  Inf       2                1479
  10 │    17              0.0            0.0  Inf       2                1479
  11 │    19              0.0            0.0  Inf       2                1479
  ⋮  │   ⋮           ⋮               ⋮           ⋮        ⋮           ⋮
  82 │    23              0.0            0.0   29.4741  12                100
  83 │    31              0.0            0.0   21.4434  12                100
  84 │    53              0.0            0.0   16.8792  12                100
  85 │    11              0.0            0.0  Inf       13                 93
  86 │    13              0.0            0.0  Inf       13                 93
  87 │    17              0.0            0.0  Inf       13                 93
  88 │    19              0.0            0.0  Inf       13                 93
  89 │    23              0.0            0.0  Inf       13                 93
  90 │    31              0.0            0.0  Inf       13                 93
  91 │    53              0.0            0.0  Inf       13                 93
                                                               70 rows omitted

In [20]:
function find_canonical_kmer_overlaps(sequences, k)
    sequence_canonical_kmers = keys.(Mycelia.count_canonical_kmers.(Kmers.DNAKmer{k}, sequences))
    canonical_kmer_intersect_sizes = zeros(length(sequence_canonical_kmers), length(sequence_canonical_kmers))
    for (a, aset) in enumerate(sequence_canonical_kmers)
        for (b, bset) in enumerate(sequence_canonical_kmers)
            canonical_kmer_intersect_sizes[a, b] = length(intersect(aset, bset))
        end
    end
    canonical_kmer_intersect_sizes
end

function find_best_kmer_intersect(canonical_kmer_intersect_sizes)
    off_diagonal_mask = .!Matrix(LinearAlgebra.I, size(canonical_kmer_intersect_sizes))
    max_off_diagonal_score = maximum(canonical_kmer_intersect_sizes[off_diagonal_mask])
    @assert max_off_diagonal_score > 0
    return findfirst(canonical_kmer_intersect_sizes .== max_off_diagonal_score)
end

function dna_pair_align(seq1, seq2, scoremodel = BioAlignments.AffineGapScoreModel(BioAlignments.EDNAFULL, gap_open=-5, gap_extend=-1))
    BioAlignments.pairalign(BioAlignments.OverlapAlignment(), seq1, seq2, scoremodel)
end

function find_best_alignment(seq1, seq2, scoremodel = BioAlignments.AffineGapScoreModel(BioAlignments.EDNAFULL, gap_open=-5, gap_extend=-1))
    forward_alignment = dna_pair_align(seq1, seq2, scoremodel)
    reverse_complement_alignment = dna_pair_align(seq1, BioSequences.reverse_complement(seq2), scoremodel)
    if BioAlignments.score(forward_alignment) > BioAlignments.score(reverse_complement_alignment)
        best_alignment = forward_alignment
    else
        best_alignment = reverse_complement_alignment
    end
    return best_alignment
end

function pairwise_align_sequences(sequences)
    best_pairwise_alignments = Array{Any}(undef, length(sequences), length(sequences))
    ProgressMeter.@showprogress for (a, a_seq) in enumerate(sequences)
        for (b, b_seq) in enumerate(sequences)
            best_pairwise_alignments[a, b] = find_best_alignment(a_seq, b_seq)
        end
    end
    best_pairwise_alignments
end

function find_best_alignment(best_pairwise_alignments)
    alignment_scores = BioAlignments.score.(best_pairwise_alignments)
    off_diagonal_mask = .!Matrix(LinearAlgebra.I, size(best_pairwise_alignments))
    max_off_diagonal_score = maximum(alignment_scores[off_diagonal_mask])
    return findfirst(alignment_scores .== max_off_diagonal_score)
end

"""
pass in alignment_result.aln or BioAlignments.alignment(alignment_result)
"""
function consensus_sequence(alignment)
    consensus_symbols = BioSymbols.DNA[]
    for alignment_tuple in collect(alignment)
        push!(consensus_symbols, rand(filter(x -> x != BioSymbols.DNA_Gap, alignment_tuple)))
    end
    consensus_seq = BioSequences.LongDNA{2}(consensus_symbols)
    return consensus_seq
end

consensus_sequence

In [21]:
assembly_sequences = deepcopy(connected_component_sequences)

13-element Vector{BioSequences.LongSequence{BioSequences.DNAAlphabet{2}}}:
 TTGGCCCTTGACTTCCCAGGCGGAAGTTCAGGCTCCCCG…GCCCAGATGTGGCTACTGTTGTACTTTCACAGGAGAGAT
 TGGTTCCCCCTCAGACATCCACATGAGCCAGCCACTTCC…ACCACTCGGGTGGGTGCCAGGATTACCGTATAGACAGTG
 TGTAATTCAGTTCGCCACGTGGACGTTGGACCCCGGAAC…GACAAAAATGGACATGTAATTGGCCTGTATGGAAATGGT
 GGCTGAAATCTACCAGCCGTCATCACCTCACTCGGAGGC…GTGTCCCCCTTTTTTGTGACTTCCACAGCAACAATAGAC
 TTGGCCCGTGTCCAATAAGGGAGCCGCACCACAAGTCTT…TCCATACCTCTAGCATGTCCTCTGTTGTCATCCACTCTC
 GTAGCAGCCGGCTTGTCAATATGCTAAGACGCGGTGGAG…CACTGGTCTCATCAACAGATGGGGAAAAGTGGGCAAAAA
 TTCGTAATGCTCCCCTCCTCAAAGCAGTCAACTGCGGGT…TCCATTTTTGTCAATTATCGGGGAGCCTGAACTTCCGCC
 GGGGAAAAGTGGGCAAAAAAGAGGCCATCAAAATCCTCA…GTGCCTATTGTTGCTGTGGAAGTCACAAAAAAGGGGGAC
 TCAAAATCCTCACAAAATTCAAGGCTGACGTGGGCACCA…TGGTGTCTATTGTTGCTGTGGAAGTCACAAAAAAGGGGG
 CTTCAGTTTCGCCGATTGCTCGGCGCACTTGATAAATGG…TTCTCTCTTTCCCAAGTATGGAACATCGGTCCACTCTGT
 AGGGGTCTTGTCCTCCATGTACTCATTCTCTAAACTCCA…GGTTGTTGTGAAGCTCGAATCGCAACTCACCGGTACAGC
 GATGGGGAAAAGTGGGCAAAAAAGAGGCCATCA

In [22]:
canonical_kmer_intersect_sizes = find_canonical_kmer_overlaps(assembly_sequences, assembly_k)
max_canonical_kmer_intersect_index = find_best_kmer_intersect(canonical_kmer_intersect_sizes)
best_alignment = find_best_alignment(assembly_sequences[[Tuple(max_canonical_kmer_intersect_index)...]]..., BioAlignments.AffineGapScoreModel(BioAlignments.EDNAFULL, gap_open=-5, gap_extend=-2))

BioAlignments.PairwiseAlignmentResult{Int64, BioSequences.LongSequence{BioSequences.DNAAlphabet{2}}, BioSequences.LongSequence{BioSequences.DNAAlphabet{2}}}:
  score: 7386
  seq:    0 ------------------------------------------------------------    0
                                                                        
  ref:    1 ATCTCTCCTGTGAAAGTACAACAGTAGCCACATCTGGGCATAAGACTTGCCCAAGCATGC   60

  seq:    0 ------------------------------------------------------------    0
                                                                        
  ref:   61 TGTTTCACTGAGTGACCAGCCTTTTCCTGGAGAAACTCTAAACGCCCTGCCTATCAACTC  120

  seq:    0 ------------------------------------------------------------    0
                                                                        
  ref:  121 ATCTTGGTGCCGGCAGGGAACTATTATTGTTCTTCCACATCGGGAGCTTGTTGAAGTGGT  180

  seq:    0 ------------------------------------------------------------    0
                                                            

In [24]:
alignment_consensus = consensus_sequence(BioAlignments.alignment(best_alignment))
assembly_sequences = [alignment_consensus, [assembly_sequence for (i, assembly_sequence) in enumerate(assembly_sequences) if !(i in Tuple(max_canonical_kmer_intersect_index))]...]
canonical_kmer_intersect_sizes = find_canonical_kmer_overlaps(assembly_sequences, assembly_k)
max_canonical_kmer_intersect_index = find_best_kmer_intersect(canonical_kmer_intersect_sizes)
best_alignment = find_best_alignment(assembly_sequences[[Tuple(max_canonical_kmer_intersect_index)...]]..., BioAlignments.AffineGapScoreModel(BioAlignments.EDNAFULL, gap_open=-5, gap_extend=-2))

BioAlignments.PairwiseAlignmentResult{Int64, BioSequences.LongSequence{BioSequences.DNAAlphabet{2}}, BioSequences.LongSequence{BioSequences.DNAAlphabet{2}}}:
  score: 4827
  seq:    0 ------------------------------------------------------------    0
                                                                        
  ref:    1 ACCATTTCCATACAGGCCAATTACATGTCCATTTTTGTCAATTATCGGGGAGCCTGAACT   60

  seq:    0 ------------------------------------------------------------    0
                                                                        
  ref:   61 TCCGCCTGGGAAGTCAAGGGCCAAGGCCCCGATTTCCCCATCAGTGGTCTTGAACACTCC  120

  seq:    0 ------------------------------------------------------------    0
                                                                        
  ref:  121 TGGTTTTGTCCGGACATTTCTGGCGCGCTCACCTGGGGCGACCGCTATCAGTTGGACTTC  180

  seq:    0 ------------------------------------------------------------    0
                                                            

In [25]:
alignment_consensus = consensus_sequence(BioAlignments.alignment(best_alignment))
assembly_sequences = [alignment_consensus, [assembly_sequence for (i, assembly_sequence) in enumerate(assembly_sequences) if !(i in Tuple(max_canonical_kmer_intersect_index))]...]
canonical_kmer_intersect_sizes = find_canonical_kmer_overlaps(assembly_sequences, assembly_k)
max_canonical_kmer_intersect_index = find_best_kmer_intersect(canonical_kmer_intersect_sizes)
best_alignment = find_best_alignment(assembly_sequences[[Tuple(max_canonical_kmer_intersect_index)...]]..., BioAlignments.AffineGapScoreModel(BioAlignments.EDNAFULL, gap_open=-5, gap_extend=-2))

BioAlignments.PairwiseAlignmentResult{Int64, BioSequences.LongSequence{BioSequences.DNAAlphabet{2}}, BioSequences.LongSequence{BioSequences.DNAAlphabet{2}}}:
  score: 846
  seq:    0 ------------------------------------------------------------    0
                                                                        
  ref:    1 ATCTCTCCTGTGAAAGTACAACAGTAGCCACATCTGGGCATAAGACTTGCCCAAGCATGC   60

  seq:    0 ------------------------------------------------------------    0
                                                                        
  ref:   61 TGTTTCACTGAGTGACCAGCCTTTTCCTGGAGAAACTCTAAACGCCCTGCCTATCAACTC  120

  seq:    0 ------------------------------------------------------------    0
                                                                        
  ref:  121 ATCTTGGTGCCGGCAGGGAACTATTATTGTTCTTCCACATCGGGAGCTTGTTGAAGTGGT  180

  seq:    0 ------------------------------------------------------------    0
                                                             

In [26]:
alignment_consensus = consensus_sequence(BioAlignments.alignment(best_alignment))
assembly_sequences = [alignment_consensus, [assembly_sequence for (i, assembly_sequence) in enumerate(assembly_sequences) if !(i in Tuple(max_canonical_kmer_intersect_index))]...]
canonical_kmer_intersect_sizes = find_canonical_kmer_overlaps(assembly_sequences, assembly_k)
max_canonical_kmer_intersect_index = find_best_kmer_intersect(canonical_kmer_intersect_sizes)
best_alignment = find_best_alignment(assembly_sequences[[Tuple(max_canonical_kmer_intersect_index)...]]..., BioAlignments.AffineGapScoreModel(BioAlignments.EDNAFULL, gap_open=-5, gap_extend=-2))

LoadError: AssertionError: max_off_diagonal_score > 0

In [28]:
final_assembly_sequences = assembly_sequences

10-element Vector{BioSequences.LongSequence{BioSequences.DNAAlphabet{2}}}:
 ATCTCTCCTGTGAAAGTACAACAGTAGCCACATCTGGGC…CGGGGAGCCTGAACTTCCGCCTGGGAAGTCAAGGGCCAA
 ACCATTTCCATACAGGCCAATTACATGTCCATTTTTGTC…GTGTCCCCCTTTTTTGTGACTTCCACAGCAACAATAGAC
 TTGGCCCGTGTCCAATAAGGGAGCCGCACCACAAGTCTT…TCCATACCTCTAGCATGTCCTCTGTTGTCATCCACTCTC
 GTAGCAGCCGGCTTGTCAATATGCTAAGACGCGGTGGAG…CACTGGTCTCATCAACAGATGGGGAAAAGTGGGCAAAAA
 GGGGAAAAGTGGGCAAAAAAGAGGCCATCAAAATCCTCA…GTGCCTATTGTTGCTGTGGAAGTCACAAAAAAGGGGGAC
 TCAAAATCCTCACAAAATTCAAGGCTGACGTGGGCACCA…TGGTGTCTATTGTTGCTGTGGAAGTCACAAAAAAGGGGG
 CTTCAGTTTCGCCGATTGCTCGGCGCACTTGATAAATGG…TTCTCTCTTTCCCAAGTATGGAACATCGGTCCACTCTGT
 AGGGGTCTTGTCCTCCATGTACTCATTCTCTAAACTCCA…GGTTGTTGTGAAGCTCGAATCGCAACTCACCGGTACAGC
 GATGGGGAAAAGTGGGCAAAAAAGAGGCCATCAAAATCC…GGGCACCATGCTTCGTATCATCAACAATCGGAAAACAAA
 TCCACTCTCCACGCCCATGGATGGACCAGGTTATTGTGA…TCACCGGTACAGCAGAGCAGATTGCGTTTGCCATGAGTC

In [29]:
sum(length.(final_assembly_sequences))

10795

In [30]:
assembly_fasta = replace(assembly_fastq, Mycelia.FASTQ_REGEX => ".assembly_k$(assembly_k).fna")
open(assembly_fasta, "w") do io
    fastx_io = FASTX.FASTA.Writer(io)
    for (i, sequence) in enumerate(final_assembly_sequences)
        identifier = "contig$(i)_length=$(length(sequence))"
        fasta_record = FASTX.FASTA.Record(identifier, sequence)
        write(fastx_io, fasta_record)
    end
    close(fastx_io)
end
assembly_fasta

"/global/cfs/cdirs/m4269/cjprybol/Mycelia/projects/variant-calling-benchmarking/data/genomes/GCF_001610725.1.fna.normalized.vcf.fna.art.100x.joint.k11.k13.k17.k19.k23.k31.k53.k89.assembly_k89.fna"